require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

RSpec/ExampleLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
