# frozen_string_literal: true

require_relative "better_content_security_policy/version"
require_relative "better_content_security_policy/content_security_policy"
require_relative "better_content_security_policy/railtie"
